name: Sync to Gitee and GitCode

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to GitCode
        run: |
          git remote add gitcode https://<azdada>:${{ secrets.GITCODE_TOKEN }}@gitcode.com/azdada/NeoAI.git
          git push gitcode main -f
